### ISSUE TITLE
Failed to get tactic from server with `--tags mateIn1`

### ISSUE THREAD

**Issue by asibahi** [marcusbuffett/chess-tactics-cli#4]
Input :
```tactics-trainer --tags mateIn1```
Output : 
```
thread 'main' panicked at 'Failed to get a new tactic from the server, exiting.: error decoding response body: expected value at line 1 column 1

Caused by:
    expected value at line 1 column 1', /Users/abdulrahmansibahi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tactics-trainer-cli-1.0.2/src/main.rs:65:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by oscarc231** [comment]
Same here. Running macOS 14.1.1:

`$ tactics-trainer`
```thread 'main' panicked at 'Failed to get a new tactic from the server, exiting.: error decoding response body: expected value at line 2 column 1

Caused by:
    expected value at line 2 column 1', /Users/myname/.cargo/registry/src/github.com-1ecc6299db9ec823/tactics-trainer-cli-1.0.2/src/main.rs:65:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
